name: Publish container image

on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  container-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - run: echo "github.actor = ${{ github.actor }}"

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    - name: Add comment
      uses: thollander/actions-comment-pull-request@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: >
          Use `docker` or `podman` to test this pull request locally.

          Local test with mock data
          ```
          podman run --rm -p 127.0.0.1:3000:3000 ghcr.io/opencast/opencast-admin-interface:main
          ```

          Proxy data from develop.opencast.org
          ```
          podman run --rm -p 127.0.0.1:3000:3000 -e PROXY_TARGET=https://develop.opencast.org localhost/opencast-admin-interface:main
          ```

          The admin interface will then be available at https://127.0.0.1:3000
